broad('Beeldhouwkunst','Beeldende%20kunst').
broad('Fotografie','Beeldende%20kunst').
broad('Schilderkunst','Beeldende%20kunst').
broad('Autobiografieën','Egodocumenten').
broad('Brieven','Egodocumenten').
broad('Dagboeken','Egodocumenten').
broad('Herinneringen','Egodocumenten').
broad('Poëzie','Egodocumenten').
broad('Communisme','Ideologieën').
broad('Conservatisme','Ideologieën').
broad('Fascisme','Ideologieën').
broad('Imperialisme','Ideologieën').
broad('Liberalisme','Ideologieën').
broad('Marxisme','Ideologieën').
broad('Nationaal-Socialisme','Ideologieën').
broad('Neofascisme','Ideologieën').
broad('Neonazisme','Ideologieën').
broad('Pacifisme','Ideologieën').
broad('Rechts-extremisme','Ideologieën').
broad('Socialisme','Ideologieën').
broad('Totalitarisme','Ideologieën').
broad('Groepsportretten','Illustraties'). 
broad('Kaartmateriaal','Illustraties'). 
broad('Plattegronden','Illustraties'). 
broad('Portretten','Illustraties').
broad('Stafkaarten','Illustraties'). 
broad('Tekeningen','Illustraties').
broad('Interneringskampen','Kampen').
broad('Boeddhisme','Religie').
broad('Christendom','Religie').
broad('Islam','Religie').
broad('Jodendom','Religie').
broad('Occultisme','Religie').
broad('Protestantisme','Religie').
broad('Rooms-Katholicisme','Religie').
broad('Duikboten','Schepen').
broad('Hospitaalschepen','Schepen').
broad('Kanonneerboten','Schepen').
broad('Kruisers','Schepen').
broad('Landingsvaartuigen','Schepen').
broad('Mijnenleggers','Schepen').
broad('Mijnenvegers','Schepen').
broad('Oorlogsschepen','Schepen').
broad('Ponten','Schepen').
broad('Slagschepen','Schepen').
broad('Torpedoboten','Schepen').
broad('Transportschepen','Schepen').
broad('Vliegboten','Schepen').
broad('Vliegdekschepen','Schepen').
broad('Landmacht ','Strijdkrachten').
broad('Luchtmacht ','Strijdkrachten').
broad('Marine ','Strijdkrachten').
broad('Vervoermiddelen','Vervoermiddelen').
broad('Ambulances','Vervoermiddelen').
broad('Auto%27s','Vervoermiddelen').
broad('Luchtschepen','Vervoermiddelen').
broad('Motorfietsen','Vervoermiddelen').
broad('Pantservoertuigen','Vervoermiddelen').
broad('Ponten','Vervoermiddelen').
broad('Rijwielen','Vervoermiddelen').
broad('Schepen','Vervoermiddelen').
broad('Tanks','Vervoermiddelen').
broad('Trams','Vervoermiddelen').
broad('Vliegtuigen','Vervoermiddelen').
broad('Voertuigen','Vervoermiddelen').
broad('Beëdigingen','Test').
broad('Accijnzen','Belastingen').
broad('Antiquariaten','Boekhandels').
broad('Berechting','Rechtspraak').
broad('Binnenvaart','Scheepvaart').
broad('Boeddhisme','Religie').
broad('Christendom','Religie').
broad('Concentratiekampsyndroom','Oorlogstrauma%27s').
broad('Contraspionage','Spionage').
broad('Corporatisme','Staatsinrichting').
broad('Drinkwatervoorziening','Watervoorziening').
broad('Dwangarbeid','Arbeid').
broad('Gezinshereniging','Hereniging').
broad('Hoogverraad','Verraad').
broad('Islam','Religie').
broad('Jeugdliteratuur','Bellettrie').
broad('Kustvaart','Scheepvaart').
broad('Landmacht','Strijdkrachten').
broad('Neofascisme','Fascisme').
broad('Neonazisme','Nationaal').
broad('Protestantisme','Christendom').
broad('Psychiatrie','Geneeskunde').
broad('Reservetroepen','Strijdkrachten').
broad('Rijksdag','Volksvertegenwoordiging').
broad('Sleepvaart','Scheepvaart').
broad('Standrecht','Berechting').
broad('Steenkolen','Kolen').
broad('Terreur','Terrorisme').
broad('Versperringen','Blokkade').
broad('Vleeswaren','Levensmiddelen').
broad('Watervoorziening','Drinkwatervoorziening').
broad('Werkverschaffing','Arbeid').
broad('Aardolie','Brandstoffen').
broad('Aftocht','Troepenbewegingen').
broad('Alcoholische%20dranken','Dranken').
broad('Atlassen','Kaartmateriaal').
broad('Atoomwapens','Wapens').
broad('Bacteriologische%20oorlogvoering','Oorlogvoering').
broad('Bankbiljetten','Geld').
broad('Cabaret','Kleinkunst').
broad('Dodenherdenking','Herdenkingen').
broad('Emigratie','Migratie').
broad('Georganiseerd%20verzet','Verzet').
broad('Geschut','Wapens').
broad('Gevechtshandelingen','Oorlogvoering').
broad('Gevechtsvliegtuigen','Vliegtuigen').
broad('Groepsportretten','Portretten').
broad('Grondwet','Wetgeving').
broad('Immigratie','Migratie').
broad('Interbellum','Vooroorlogse%20periode').
broad('Jazz','Muziek').
broad('Kampkranten','Kranten').
broad('Kolen','Brandstoffen').
broad('Koninklijke%20besluiten','Wetgeving').
broad('Kranten','Periodieken').
broad('Mannenkampen','Interneringskampen').
broad('Massa%20executies','Executies').
broad('Massagraven','Graven').
broad('Ministers','Kabinetten').
broad('Muntgeld','Geld').
broad('Auto%27s','Vervoermiddelen').
broad('Beeldhouwkunst','Beeldende%20kunst').
broad('Burgermannenkampen','Kampen').
broad('Cartoons','Illustraties').
broad('Christendom','Religie').
broad('Concentratiekampen','Kampen').
broad('Dagboeken','Egodocumenten').
broad('Doorgangskampen','Kampen').
broad('Duikboten','Schepen').
broad('Fascisme','Ideologieen').
broad('Fietsen','Vervoermiddelen').
broad('Foto%27s','Illustraties').
broad('Gijzelaarskampen','Kampen').
broad('Humanisme','Ideologieen').
broad('Interneringskampen','Kampen').
broad('Islam','Religie').
broad('Isolationisme','Ideologieen').
broad('Jongenskampen','Kampen').
broad('Karikaturen','Illustraties').
broad('Landstrijdkrachten','Strijdkrachten').
broad('Liberalisme','Ideologieen').
broad('Luchtmacht','Strijdkrachten').
broad('Mannenkampen','Kampen').
broad('Marine','Strijdkrachten').
broad('Marxisme','Ideologieen').
broad('Motorfietsen','Vervoermiddelen').
broad('Nationaal-Socialisme','Ideologieen').
broad('Nationalisme','Ideologieen').
broad('Neofascisme','Ideologieen').
broad('Neonazisme','Ideologieen').
broad('Pacifisme','Ideologieen').
broad('Pangermanisme','Ideologieen').
broad('Pan-Slavisme','Ideologieen').
broad('Protestantisme','Christendom').
broad('Rooms-katholicisme','Christendom').
broad('Schepen','Vervoermiddelen').
broad('Schilderkunst','Beeldende%20kunst').
broad('Separatisme','Ideologieen').
broad('Slagschepen','Schepen').
broad('Socialisme','Ideologieen').
broad('Spotprenten','Illustraties').
broad('Stalinisme','Ideologieen').
broad('Tekeningen','Illustraties').
broad('Totalitarisme','Ideologieen').
broad('Trams','Vervoermiddelen').
broad('Treinen','Vervoermiddelen').
broad('Vernietigingskampen','Kampen').
broad('Vliegdekschepen','Schepen').
broad('Vliegtuigen','Vervoermiddelen').
broad('Vrouwenkampen','Kampen').
broad('Werkkampen','Kampen').
broad('Zionisme','Ideologieen').